// LOCALHOST
### Get all movies
GET http://localhost:8080/movies


### Get movie by id
GET http://localhost:8080/movies/673377093dedfd839ef6cbf7


### Create movie
POST http://localhost:8080/movies HTTP/1.1
content-type: application/json

{
    "title":"Pulp Fiction",
    "description":"The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    "release_date":"1994-10-14T00:00:00.000Z",
    "movie_gender_id":4,
    "director_id":4,
    "total_minutes": 154
}


### PUT movie
PUT http://localhost:8080/movies/673377093dedfd839ef6cbf7 HTTP/1.1
content-type: application/json

{
    "title":"Pulp Fiction",
    "description":"The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    "release_date":"1994-10-14T00:00:00.000Z",
    "movie_gender_id":4,
    "director_id":4,
    "total_minutes": 156
}

### DELETE movie
DELETE http://localhost:8080/movies/673377093dedfd839ef6cbf7 HTTP/1.1

// PRODUCTION Deploy
### Get all contacts
GET https://cse-341-project2-obur.onrender.com/movies


### Get movie by id
GET https://cse-341-project2-obur.onrender.com/movies/673377093dedfd839ef6cbf7


### Create movie
POST https://cse-341-project2-obur.onrender.com/movies HTTP/1.1
content-type: application/json

{
    "title":"Pulp Fiction",
    "description":"The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    "release_date":"1994-10-14T00:00:00.000Z",
    "movie_gender_id":4,
    "director_id":4,
    "total_minutes": 154
}


### PUT contact
PUT https://cse-341-project2-obur.onrender.com/movies/673377093dedfd839ef6cbf7 HTTP/1.1
content-type: application/json

{
    "title":"Pulp Fiction",
    "description":"The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    "release_date":"1994-10-14T00:00:00.000Z",
    "movie_gender_id":4,
    "director_id":4,
    "total_minutes": 156
}


### DELETE movie
DELETE https://cse-341-project2-obur.onrender.com/movies/673377093dedfd839ef6cbf7 HTTP/1.1
